export const GATEWAY_EVENTS = [
  'activity.leave_presence',
  'activity.update_presence',
  'article.read_count_update',
  'auth.failed',
  'comment.create',
  'comment.update',
  'companion_presence.changed',
  'fn.media-update',
  'fn.ps-update',
  'fn.shiro#status',
  'fn.shiro#update',
  'gateway.connect',
  'gateway.disconnect',
  'note.create',
  'note.delete',
  'note.republish',
  'note.unpublish',
  'note.update',
  'page.update',
  'PAGE_UPDATED',
  'post.create',
  'post.delete',
  'post.republish',
  'post.unpublish',
  'post.update',
  'recently.create',
  'recently.delete',
  'say.create',
  'say.delete',
  'say.update',
  'translation.create',
  'translation.update',
  'visitor.offline',
  'visitor.online',
] as const

export type GatewayEvent = (typeof GATEWAY_EVENTS)[number]
